USE [master]
GO
/****** Object:  Database [FoodDB]    Script Date: 3/3/2024 12:03:11 PM ******/
CREATE DATABASE [FoodDB]

ALTER DATABASE [FoodDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FoodDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FoodDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FoodDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FoodDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [FoodDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FoodDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FoodDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FoodDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FoodDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FoodDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FoodDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FoodDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FoodDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FoodDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [FoodDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FoodDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FoodDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FoodDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FoodDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FoodDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FoodDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FoodDB] SET RECOVERY FULL 
GO
ALTER DATABASE [FoodDB] SET  MULTI_USER 
GO
ALTER DATABASE [FoodDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FoodDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FoodDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FoodDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FoodDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FoodDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'FoodDB', N'ON'
GO
ALTER DATABASE [FoodDB] SET QUERY_STORE = OFF
GO
USE [FoodDB]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 3/3/2024 12:03:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[categories]    Script Date: 3/3/2024 12:03:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[categories](
	[CategoryId] [int] IDENTITY(1,1) NOT NULL,
	[CategoryName] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_categories] PRIMARY KEY CLUSTERED 
(
	[CategoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[clients]    Script Date: 3/3/2024 12:03:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[clients](
	[ClientId] [int] IDENTITY(1,1) NOT NULL,
	[ClientName] [nvarchar](max) NOT NULL,
	[Address] [nvarchar](max) NOT NULL,
	[Email] [nvarchar](max) NULL,
	[Password] [nvarchar](max) NULL,
	[Phone] [int] NOT NULL,
 CONSTRAINT [PK_clients] PRIMARY KEY CLUSTERED 
(
	[ClientId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[menus]    Script Date: 3/3/2024 12:03:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[menus](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
	[price] [float] NOT NULL,
	[CategoryId] [int] NOT NULL,
 CONSTRAINT [PK_menus] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[orderDetailes]    Script Date: 3/3/2024 12:03:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[orderDetailes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[order_Id] [int] NOT NULL,
	[menu_Id] [int] NOT NULL,
	[OrderId] [int] NOT NULL,
	[menuId] [int] NOT NULL,
 CONSTRAINT [PK_orderDetailes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[orders]    Script Date: 3/3/2024 12:03:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[orders](
	[OrderId] [int] IDENTITY(1,1) NOT NULL,
	[Total] [float] NOT NULL,
	[Client_id] [int] NOT NULL,
 CONSTRAINT [PK_orders] PRIMARY KEY CLUSTERED 
(
	[OrderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20240302183420_createTable', N'9.0.0-preview.1.24081.2')
GO
/****** Object:  Index [IX_menus_CategoryId]    Script Date: 3/3/2024 12:03:11 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_menus_CategoryId] ON [dbo].[menus]
(
	[CategoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_orderDetailes_menuId]    Script Date: 3/3/2024 12:03:11 PM ******/
CREATE NONCLUSTERED INDEX [IX_orderDetailes_menuId] ON [dbo].[orderDetailes]
(
	[menuId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_orderDetailes_OrderId]    Script Date: 3/3/2024 12:03:11 PM ******/
CREATE NONCLUSTERED INDEX [IX_orderDetailes_OrderId] ON [dbo].[orderDetailes]
(
	[OrderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_orders_Client_id]    Script Date: 3/3/2024 12:03:11 PM ******/
CREATE NONCLUSTERED INDEX [IX_orders_Client_id] ON [dbo].[orders]
(
	[Client_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[menus]  WITH CHECK ADD  CONSTRAINT [FK_menus_categories_CategoryId] FOREIGN KEY([CategoryId])
REFERENCES [dbo].[categories] ([CategoryId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[menus] CHECK CONSTRAINT [FK_menus_categories_CategoryId]
GO
ALTER TABLE [dbo].[orderDetailes]  WITH CHECK ADD  CONSTRAINT [FK_orderDetailes_menus_menuId] FOREIGN KEY([menuId])
REFERENCES [dbo].[menus] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[orderDetailes] CHECK CONSTRAINT [FK_orderDetailes_menus_menuId]
GO
ALTER TABLE [dbo].[orderDetailes]  WITH CHECK ADD  CONSTRAINT [FK_orderDetailes_orders_OrderId] FOREIGN KEY([OrderId])
REFERENCES [dbo].[orders] ([OrderId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[orderDetailes] CHECK CONSTRAINT [FK_orderDetailes_orders_OrderId]
GO
ALTER TABLE [dbo].[orders]  WITH CHECK ADD  CONSTRAINT [FK_orders_clients_Client_id] FOREIGN KEY([Client_id])
REFERENCES [dbo].[clients] ([ClientId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[orders] CHECK CONSTRAINT [FK_orders_clients_Client_id]
GO
USE [master]
GO
ALTER DATABASE [FoodDB] SET  READ_WRITE 
GO
